// Generated by CoffeeScript 1.9.3
(function() {
  var MojioSDK, should;

  MojioSDK = require('../../src/nodejs/MojioSDK');

  should = require('should');

  describe('Node Mojio Auth SDK', function() {
    var sdk, testErrorResult;
    sdk = new MojioSDK();
    testErrorResult = function(error, result) {
      (error === null).should.be["true"];
      return (result !== null).should.be["true"];
    };
    return it('can authorize', function(done) {
      this.timeout(2000);
      return sdk.authorize({
        type: "token",
        user: "unittest@moj.io",
        password: "mojioRocks"
      }, function(error, result) {
        testErrorResult(error, result);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=NodeAuthSDK_test.js.map
