// Generated by CoffeeScript 1.9.3
(function() {
  var FormUrlencoded, Http, MojioPushSDK, MojioSharingSDK, SignalR, _,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Http = require('./HttpNodeWrapper');

  SignalR = require('./SignalRNodeWrapper');

  FormUrlencoded = require('form-urlencoded');

  _ = require('underscore');

  MojioSharingSDK = require('./MojioSharingSDK');

  module.exports = MojioPushSDK = (function(superClass) {
    var defaultTransports;

    extend(MojioPushSDK, superClass);

    defaultTransports = {
      signalr: {},
      httpPost: {}
    };

    function MojioPushSDK(transports, options) {
      if (options == null) {
        options = {};
      }
      _.extend(this, transports);
      MojioPushSDK.__super__.constructor.call(this, options);
    }

    MojioPushSDK.prototype.observe = function(key, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioPushSDK.prototype.fields = function(fields, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioPushSDK.prototype.where = function(clause, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioPushSDK.prototype.transport = function(transport, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioPushSDK.prototype.throttle = function(throttle, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioPushSDK.prototype.debounce = function(debounce, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioPushSDK.prototype.timing = function(state, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    return MojioPushSDK;

  })(MojioSharingSDK);

}).call(this);

//# sourceMappingURL=MojioPushSDK.js.map
