// Generated by CoffeeScript 1.9.3
(function() {
  var FormUrlencoded, Http, MojioBaseSDK, SignalR, _;

  Http = require('./HttpNodeWrapper');

  SignalR = require('./SignalRNodeWrapper');

  FormUrlencoded = require('form-urlencoded');

  _ = require('underscore');

  module.exports = MojioBaseSDK = (function() {
    function MojioBaseSDK(options) {
      if (options == null) {
        options = {};
      }
      MojioBaseSDK.__super__.constructor.call(this, options);
    }

    MojioBaseSDK.prototype.mock = function(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioBaseSDK.prototype.callback = function(callback) {
      callback(null, true);
      return this;
    };

    return MojioBaseSDK;

  })();

}).call(this);

//# sourceMappingURL=MojioBaseSDK.js.map
