// Generated by CoffeeScript 1.9.3
(function() {
  var MojioPushSDK, MojioSDK,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MojioPushSDK = require('./MojioPushSDK');

  module.exports = MojioSDK = (function(superClass) {
    extend(MojioSDK, superClass);

    function MojioSDK(options) {
      if (options == null) {
        options = {};
      }
      MojioSDK.__super__.constructor.call(this, options);
    }

    return MojioSDK;

  })(MojioPushSDK);

}).call(this);

//# sourceMappingURL=MojioSDK.js.map
