// Generated by CoffeeScript 1.9.3
(function() {
  var FormUrlencoded, Http, MojioAuthSDK, MojioRestSDK, SignalR, _,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Http = require('./HttpNodeWrapper');

  SignalR = require('./SignalRNodeWrapper');

  FormUrlencoded = require('form-urlencoded');

  _ = require('underscore');

  MojioAuthSDK = require('./MojioAuthSDK');

  module.exports = MojioRestSDK = (function(superClass) {
    extend(MojioRestSDK, superClass);

    function MojioRestSDK(options) {
      if (options == null) {
        options = {};
      }
      MojioRestSDK.__super__.constructor.call(this, options);
    }

    MojioRestSDK.prototype.save = function(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioRestSDK.prototype.update = function(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioRestSDK.prototype.create = function(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioRestSDK.prototype["for"] = function(user, callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioRestSDK.prototype.query = function(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    MojioRestSDK.prototype.destroy = function(callback) {
      if ((callback != null)) {
        this.callback(callback);
      }
      return this;
    };

    return MojioRestSDK;

  })(MojioAuthSDK);

}).call(this);

//# sourceMappingURL=MojioRestSDK.js.map
