// Generated by CoffeeScript 1.9.3
(function() {
  var SignalRCordovaWrapper,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = SignalRCordovaWrapper = (function() {
    SignalRCordovaWrapper.prototype.observer_callbacks = {};

    SignalRCordovaWrapper.prototype.observer_registry = function(entity) {
      return null;
    };

    function SignalRCordovaWrapper(url, hubNames) {
      this.observer_registry = bind(this.observer_registry, this);
      this.url = url;
      this.hubs = {};
      this.signalr = null;
      this.connectionStatus = false;
    }

    SignalRCordovaWrapper.prototype.getHub = function(which, callback) {
      return callback("Titanium support for signalR not available.", null);
    };

    SignalRCordovaWrapper.prototype.setCallback = function(id, futureCallback) {};

    SignalRCordovaWrapper.prototype.removeCallback = function(id, pastCallback) {};

    SignalRCordovaWrapper.prototype.subscribe = function(hubName, method, observerId, subject, futureCallback, callback) {
      return callback("Titanium support for signalR not available.", null);
    };

    SignalRCordovaWrapper.prototype.unsubscribe = function(hubName, method, observerId, subject, pastCallback, callback) {
      return callback("Titanium support for signalR not available.", null);
    };

    return SignalRCordovaWrapper;

  })();

}).call(this);

//# sourceMappingURL=SignalRCordovaWrapper.js.map
